# Generated by Django 5.2.8 on 2025-11-27 00:19

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('FamilyMemberID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('fiancée', 'Fiancée'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('passport_number', models.CharField(max_length=35)),
                ('passport_expiry_date', models.DateField()),
                ('passport_issue_date', models.DateField()),
                ('passport_issue_country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
