# Generated by Django 5.2.8 on 2025-11-27 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_familymember_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='middle_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
