# Generated by Django 5.2.8 on 2025-11-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_rename_name_familymember_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='status',
        ),
    ]
